name = "colour-scheme-generator"
compatibility_date = "2024-06-29"

# Pages configuration
pages_build_output_dir = "src"

# Environment variables (if needed)
[env.production.vars]
# Add any environment variables here if needed
